### ISSUE TITLE
RLIMIT_DATA和 RLIMIT_AS的选择

### ISSUE THREAD

**Issue by virusdefender** [lodevil/Lo-runner#10]
我看你的项目使用的是 `setrlimit(RLIMIT_DATA, &rl)` 来限制内存的，而 hustoj 的判题端使用的是`RLIMIT_AS`，代码在 https://github.com/zhblue/hustoj/blob/master/trunk/core/judge_client/judge_client.cc#L1565

我的理解是`RLIMIT_DATA`就只能限制代码数据段的内存占用，比如代码中已经定义的数组，而`RLIMIT_AS`是限制了整个进程的虚拟地址空间，也能控制 `malloc` 或者 `new` 的内存了。

不知道我理解的对么，你选择 `RLIMIT_DATA` 的理由是什么呢？谢谢

**Comment by dojiong** [comment]
代码中已定义的数组包括两种：
1. 函数体内的，在栈中分配，由RLIMIT_STACK来限制
2. 全局的，属于已初始或未初始的变量，由RLIMIT_DATA限制

另外RLIMIT_DATA同样也影响堆。

RLIMIT_AS是限制进程的虚拟内存大小，即内存地址空间的大小，是不能反应一个程序使用物理内存的大小的。

**Comment by dojiong** [comment]
http://linux.die.net/man/2/getrlimit
可以看看里面各种限制具体的含义

**Comment by virusdefender** [comment]
``` c
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/time.h>
#include <sys/resource.h>
int main()
{
    int *a = NULL;
    // 150M
    int v = 150000000;
    struct rlimit memory_limit;
    // 90M
    memory_limit.rlim_cur = memory_limit.rlim_max = 90000000;
    setrlimit(RLIMIT_AS, &memory_limit);
    //setrlimit(RLIMIT_DATA, &memory_limit);
    a = (int *)malloc(v);
    if(a == NULL){
        printf("error\n");
    }
    else {
        memset(a, 0, v);
        printf("success\n");
    }
    return 0;
}

```

但是我使用上面的代码测试，`RLIMIT_DATA` 仍然能成功的分配内存，而 `RLIMIT_AS` 会导致内存分配失败。

文档上说的`This limit affects calls to brk(2) and sbrk(2)`，我测试 `malloc` 大内存的时候使用到了 `mmap`。

**Comment by dojiong** [comment]
又翻了下文档，glibc的malloc有两种分配内存的方式，小内存是在堆上面分配（可以被RLIMIT_DATA影响），但是超过阈值的内存分配是通过mmap来分配的，mmap分配的不在堆上，而他产生的地址空间是受RLIMIT_AS影响的。

所以这里应该是RLIMIT_DATA和RLIMIT_AS都要做限制，但是由于地址空间里面有些不是进程直接分配的内存，因此设置限制的时候乘以2了。

不过这个bug不影响测评的结果（最后会再次校验内存的使用情况）。

Thanks!
