### ISSUE TITLE
想知道有木有trace功能的白名单

### ISSUE THREAD

**Issue by springhack** [lodevil/Lo-runner#11]
写了个vj想要添加一个插件支持，变成 vj && oj 双混合模式，基本差不多但是不知道哪些system calls该放行，看了hustoj的源码［大雾，Ubuntu Server 15.10 32位  0.0

So 来请求帮助了 😂

**Comment by dojiong** [comment]
strace 可以看程序运行的系统调用
/usr/include/asm/unistd*.h里面有系统调用对应的调用号

SpringHack notifications@github.com于2016年5月2日周一 12:12写道：

**Comment by dojiong** [comment]
``` python
import re

with open('/usr/include/asm/unistd_64.h') as f:
    defs = re.findall(r'#define __NR_(\w+)\s+(\d+)', f.read())

for name, num in defs:
    print(name, num)
```
