### ISSUE TITLE
怎么设置files参数？

### ISSUE THREAD

**Issue by Bluefissure** [lodevil/Lo-runner#12]
我在设置中这样设置，
runcfg['trace'] = True
runcfg['calls'] = [0,1,2,3,5,9,10,11,12,21,59,158,231]
runcfg['files'] = {'/etc/ld.so.cache': 0}
然而运行时返回的结果是RE，具体如下
{'re_file': '/etc/ld.so.cache', 'memoryused': 156, 'result': 5, 'timeused': 0, 're_file_flag': 524288}
求问这个files参数是什么意思？应该怎么设置？

**Comment by dojiong** [comment]
re_file_flag是O_CLOEXEC，open的flag里面有O_CLOEXEC
这个flag可以忽略，{'/etc/ld.so.cache': 0o2000000}就可以了

open的高位flag有些是可以直接忽略的，你可以修改lorun/cext/access.c：fileAccess里面的代码，忽略高位的flag
