### ISSUE TITLE
MAC 上无法编译成功，好像是因为 sys/user.h文件和linux不一样 

### ISSUE THREAD

**Issue by DmuMenDuo** [lodevil/Lo-runner#13]
(oj) ➜  Lo-runner git:(master) ✗ python setup.py install
running install
running build
running build_py
running build_ext
building 'lorun/_lorun_ext' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/menduo/anaconda3/envs/oj/include -arch x86_64 -I/Users/menduo/anaconda3/envs/oj/include -arch x86_64 -I/Users/menduo/anaconda3/envs/oj/include/python3.6m -c lorun/cext/lorun.c -o build/temp.macosx-10.7-x86_64-3.6/lorun/cext/lorun.o
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/menduo/anaconda3/envs/oj/include -arch x86_64 -I/Users/menduo/anaconda3/envs/oj/include -arch x86_64 -I/Users/menduo/anaconda3/envs/oj/include/python3.6m -c lorun/cext/convert.c -o build/temp.macosx-10.7-x86_64-3.6/lorun/cext/convert.o
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/menduo/anaconda3/envs/oj/include -arch x86_64 -I/Users/menduo/anaconda3/envs/oj/include -arch x86_64 -I/Users/menduo/anaconda3/envs/oj/include/python3.6m -c lorun/cext/access.c -o build/temp.macosx-10.7-x86_64-3.6/lorun/cext/access.o
In file included from lorun/cext/access.c:19:
lorun/cext/access.h:39:56: warning: declaration of 'struct user_regs_struct' will not be visible outside of this function [-Wvisibility]
int checkAccess(struct Runobj *runobj, int pid, struct user_regs_struct *regs);
                                                       ^
lorun/cext/access.c:20:2: error: invalid preprocessing directive
#includegc <sys/syscall.h>
 ^
lorun/cext/access.c:45:56: warning: declaration of 'struct user_regs_struct' will not be visible outside of this function [-Wvisibility]
int checkAccess(struct Runobj *runobj, int pid, struct user_regs_struct *regs) {
                                                       ^
lorun/cext/access.c:45:5: error: conflicting types for 'checkAccess'
int checkAccess(struct Runobj *runobj, int pid, struct user_regs_struct *regs) {
    ^
lorun/cext/access.h:39:5: note: previous declaration is here
int checkAccess(struct Runobj *runobj, int pid, struct user_regs_struct *regs);
    ^
lorun/cext/access.c:46:27: error: incomplete definition of type 'struct user_regs_struct'
    if (!runobj->inttable[REG_SYS_CALL(regs)])
                          ^~~~~~~~~~~~~~~~~~
lorun/cext/access.h:30:33: note: expanded from macro 'REG_SYS_CALL'
    #define REG_SYS_CALL(x) ((x)->orig_rax)
                             ~~~^
lorun/cext/access.c:45:56: note: forward declaration of 'struct user_regs_struct'
int checkAccess(struct Runobj *runobj, int pid, struct user_regs_struct *regs) {
                                                       ^
lorun/cext/access.c:49:13: error: incomplete definition of type 'struct user_regs_struct'
    switch (REG_SYS_CALL(regs)) {
            ^~~~~~~~~~~~~~~~~~
lorun/cext/access.h:30:33: note: expanded from macro 'REG_SYS_CALL'
    #define REG_SYS_CALL(x) ((x)->orig_rax)
                             ~~~^
lorun/cext/access.c:45:56: note: forward declaration of 'struct user_regs_struct'
int checkAccess(struct Runobj *runobj, int pid, struct user_regs_struct *regs) {
                                                       ^
2 warnings and 4 errors generated.
error: command 'gcc' failed with exit status 1

---------------报错信息----------------

sys/user.h文件 
-----------------------------------------
#ifndef	_SYS_USER_H_
#define	_SYS_USER_H_

#include <sys/appleapiopts.h>
struct waitq_set;
/* stuff that *used* to be included by user.h, or is now needed */
#include <errno.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <sys/ucred.h>
#include <sys/uio.h>
#include <sys/vm.h>		/* XXX */
#include <sys/sysctl.h>


/*
 * Per process structure containing data that isn't needed in core
 * when the process isn't running (esp. when swapped out).
 * This structure may or may not be at the same kernel address
 * in all processes.
 */
 
struct	user {
  /* NOT USED ANYMORE */
};

#endif	/* !_SYS_USER_H_ */

**Comment by skyzh** [comment]
darwin 和 Linux 可能不一样，可以用 docker 开个 Linux 环境。

**Comment by DmuMenDuo** [comment]
mac有点坑, 我发现ptrace.h也不一样。只能放docker里了

**Comment by dojiong** [comment]
仅支持linux
