### ISSUE TITLE
沙盒中（python）调用其他库

### ISSUE THREAD

**Issue by DmuMenDuo** [lodevil/Lo-runner#14]
请问，我在沙盒中使用python的import numpy的时候发现会调用失败。
好像所有的import操作都会失败。目前找了好久也没找到原因。
所以想问一下作者，我想在执行的程序里面import其他库应该怎么做？
出错信息：
ImportError: liblapack.so.3: failed to map segment from shared object

**Comment by skyzh** [comment]
你是不是开启了 ptrace 功能，或者限制了文件访问？

**Comment by DmuMenDuo** [comment]
并没有 我没设置ptrace  = true 。刚才看源码的时候还注意了一下 @SkyZH 。

**Comment by dojiong** [comment]
系统调用被限制了，你可以用strace看一下跑python脚本需要用到哪些调用和文件
