### ISSUE TITLE
Presentation Error when using 'rU' open mode

### ISSUE THREAD

**Issue by skyzh** [lodevil/Lo-runner#2]
Some code:

```
fin = open(inFile, 'rU')
```

inFile is data from MySQL Database, and this data is from PHP textarea input by user.
I use vim to see the inFile, and find ^M at the end of each line.
So I use 'rU' open mode instead of 'r'.
But when lo-runner compare between answer and user out file, it gives out Presentation Error.
Out file doesn't have ^M.

**Comment by dojiong** [comment]
`diff` compares byte to byte，it does not support universal newlines.

**Comment by skyzh** [comment]
Thanks.
I replace '\r\n' with '\n' in PHP finally.
