### ISSUE TITLE
PE after latest commit

### ISSUE THREAD

**Issue by skyzh** [lodevil/Lo-runner#3]
... When I start using latest version of Lo-runner...
There are all 'PE' status

But using  https://github.com/lodevil/Lo-runner/commit/537af2c640a16ee3dedd416f3c8bc4f08fcea0cb is OK.

**Comment by skyzh** [comment]
http://kids.org.cn/oj/status/view/29 AC using https://github.com/lodevil/Lo-runner/commit/537af2c640a16ee3dedd416f3c8bc4f08fcea0cb
http://kids.org.cn/oj/status/view/27 PE using HEAD Version

I've checked each data seriously...

**Comment by SkyZH** [comment]
http://kids.org.cn/oj/status/view/29 AC using https://github.com/lodevil/Lo-runner/commit/537af2c640a16ee3dedd416f3c8bc4f08fcea0cb
http://kids.org.cn/oj/status/view/27 PE using HEAD Version

I've checked each data seriously...

**Comment by skyzh** [comment]
I noticed that vim shows that output file of user's program doesn't have EOF, the HEAD version can't judge it correctly.

**Comment by skyzh** [comment]
I've compared data and user output in binary mode and surprisingly find them the same...

**Comment by skyzh** [comment]
Sometimes user output doesn't have a EOF... I don't know why...

**Comment by skyzh** [comment]
Fixed in https://github.com/SkyZH/Lo-runner/commit/f8977361741ea0501a76fe36551a82c3dcf733eb , Merge Please.
