### ISSUE TITLE
64位Ubuntu下内存读不准

### ISSUE THREAD

**Issue by doveccl** [lodevil/Lo-runner#8]
lorun在32位系统下表现很好，然而在64位Ubuntu下（我测试了12.04和14.04两个LTS版本），都会出现内存读不准的问题，请问有什么方法可以解决么？

**Comment by dojiong** [comment]
你是说程序的内存消耗结果不对么？

**Comment by doveccl** [comment]
是的，在64位ubuntu下会出现内存消耗评测不准的问题

**Comment by skyzh** [comment]
http://kids.org.cn/oj/status/view/508
http://kids.org.cn/oj/status/view/507
http://kids.org.cn/oj/status/view/506

自从 1669914e24e39cb5459a55f4043e93ea334e5fa4 后，显示的内存值就变得特别大，因此后来这个 OJ 上的 lo-runner 换成了之前的版本。
系统是 Ubuntu 15.10 64bit

**Comment by dojiong** [comment]
fixed
